name: Build & Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    name: build & test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: 'https://registry.npmjs.org/'

      - name: Install Node dependencies
        run: npm ci

      - name: Run Node build (if present)
        run: npm run build --if-present
    
      - name: Run Tests (if present)
        run: npm test --if-present
